"""initial migration

Revision ID: 7b32d52fc708
Revises:
Create Date: 2026-03-14 17:52:18.943264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
STRING_LINGTH = 256
CASCADE = "CASCADE"
ID = "id"

# revision identifiers, used by Alembic.
revision: str = "7b32d52fc708"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column(ID, sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=STRING_LINGTH), nullable=False),
        sa.Column("opening_balance", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint(ID),
    )
    op.create_table(
        "categories",
        sa.Column(ID, sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=STRING_LINGTH), nullable=False),
        sa.Column(
            "type", sa.Enum("INCOME", "EXPENSE", name="categorytype"), nullable=False
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint(ID),
    )
    op.create_table(
        "transactions",
        sa.Column(ID, sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("amount", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete=CASCADE),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete=CASCADE),
        sa.PrimaryKeyConstraint(ID),
    )
    op.create_table(
        "transfers",
        sa.Column(ID, sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("from_account_id", sa.Integer(), nullable=False),
        sa.Column("to_account_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_account_id"], ["accounts.id"], ondelete=CASCADE
        ),
        sa.ForeignKeyConstraint(["to_account_id"], ["accounts.id"], ondelete=CASCADE),
        sa.PrimaryKeyConstraint(ID),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transfers")
    op.drop_table("transactions")
    op.drop_table("categories")
    op.drop_table("accounts")
    # ### end Alembic commands ###
