"""Initial Migration

Revision ID: a887187c0ea0
Revises: 7b32d52fc708
Create Date: 2026-03-14 20:53:45.522685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a887187c0ea0"
down_revision: Union[str, None] = "7b32d52fc708"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transfers", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transfers", "is_deleted")
    # ### end Alembic commands ###
